### ISSUE TITLE
register problem CORS policy

### ISSUE THREAD

**Issue by kfranco89** [STS-Rosario/carpoolear_backend#95]
hi i have problem to register new user i got this msg "**Access to XMLHttpRequest at 'http://localhost:8080/api/users' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."**

![screenshot from 2019-02-19 22-03-39](https://user-images.githubusercontent.com/46143528/53063602-a46d3200-3492-11e9-83c1-70880e93b4c0.png)

**Comment by p4bl1t0** [comment]
@kfranco89 hi there

In wich URL do you have running the backend? It seems that the frontend is running at localhost:8081 and trying to connect to the backend at localhost:8080, is that correct?

**Comment by miguelbalparda** [comment]
This doesn't seem to be a problem with the app but with the way you set it up locally. 
The cause is that localhost:8081 and localhost:8080 are different [origins](https://stackoverflow.com/questions/18642828/origin-origin-is-not-allowed-by-access-control-allow-origin).
IMO the best way to solve this is by using a vhost and a fake domain like carpoolear-test.com and not localhost, which is known to have issues specially in [Chrome](https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin). 
Another way to solve this is adding a line in your .htaccess containing
`Header set Access-Control-Allow-Origin "*"` but I would definitely recommend using a domain to make things easier.

**Comment by kfranco89** [comment]
> @kfranco89 hi there
> 
> In wich URL do you have running the backend? It seems that the frontend is running at localhost:8081 and trying to connect to the backend at localhost:8080, is that correct?

yes  because when i ran server and front was set by default

**Comment by kfranco89** [comment]
> This doesn't seem to be a problem with the app but with the way you set it up locally.
> The cause is that localhost:8081 and localhost:8080 are different [origins](https://stackoverflow.com/questions/18642828/origin-origin-is-not-allowed-by-access-control-allow-origin).
> IMO the best way to solve this is by using a vhost and a fake domain like carpoolear-test.com and not localhost, which is known to have issues specially in [Chrome](https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin).
> Another way to solve this is adding a line in your .htaccess containing
> `Header set Access-Control-Allow-Origin "*"` but I would definitely recommend using a domain to make things easier.

i use fake host by adding into etc/host but doest work  and add it into .htaccess back site but doest work

**Comment by p4bl1t0** [comment]
You have to configure a local site in Apache for the carpoolear_backend/public folder. Point your fake host to that folder. Then as @miguelbalparda said add the Access-Control-Allow-Origin to your htaccess

**Comment by kfranco89** [comment]
i should use a chrome extension "Allow CORS: Access-Control-Allow-Origin"  thanks you

**Comment by kfranco89** [comment]
I have try to solve it but no luck,  this is how i try it 
1. Add it to .htaccess
2. Create Cors.php and mod Kernel.php

Some help please.

![Captura de pantalla de 2019-04-08 17-25-58](https://user-images.githubusercontent.com/46143528/55761118-decf6600-5a23-11e9-9f47-9f7caefd396c.png)
![Captura de pantalla de 2019-04-08 17-26-17](https://user-images.githubusercontent.com/46143528/55761119-decf6600-5a23-11e9-9152-67feb71dd92a.png)
![Captura de pantalla de 2019-04-08 17-27-24](https://user-images.githubusercontent.com/46143528/55761120-df67fc80-5a23-11e9-8011-7edbfb0ca782.png)

**Comment by miguelbalparda** [comment]
I created a vagrant based VM to ease the requirements to contribute to this project. This does not require extra configs and configures both the frontend and the backend together, you might want to try it: https://github.com/miguelbalparda/carpoolear_vm

**Comment by kfranco89** [comment]
> I created a vagrant based VM to ease the requirements to contribute to this project. This does not require extra configs and configures both the frontend and the backend together, you might want to try it: https://github.com/miguelbalparda/carpoolear_vm

Im using aws with route 53 and load balancers  where should i config cors access ?

**Comment by miguelbalparda** [comment]
What's the URL of your project?

**Comment by kfranco89** [comment]
groove.link  i have create a sub url for server and use main url for front , so i put 

Header set aAccess-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods: GET, POST, PUT
Heeader set Access-Control-Allow-Headers: Content-Type

into public .htaccess carpool_backend
but is not working

**Comment by miguelbalparda** [comment]
I'm not really sure but I don't think you are supposed to do it like that if you are using a "real" server. Most of the steps you need if you already have a working server can be found in my Vagrant VM, you don't need to use a subdomain but to link the correct folders as shown there in line [31 and 32](https://github.com/miguelbalparda/carpoolear_vm/blob/master/install.sh#L32).
